### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by demis001** [VDBWRAIR/pathdiscov#293]
Hi Guys!

This step fialed .. any idea?

 `wget https://raw.githubusercontent.com/necrolyte2/bootstrap_vi/master/bootstrap_vi.py -O- | python - pathdiscov --prompt="(pathdiscov)"`

This is what I got:

```
virtualenv-20.0.28/tests/unit/seed/wheels/test_wheels_util.py
virtualenv-20.0.28/tests/unit/test_run.py
virtualenv-20.0.28/tests/unit/test_util.py
virtualenv-20.0.28/tox.ini
Traceback (most recent call last):
  File "<stdin>", line 132, in <module>
  File "<stdin>", line 129, in main
  File "<stdin>", line 125, in bootstrap_vi
  File "<stdin>", line 109, in create_virtualenv
  File "/home/ddjima/anaconda3/envs/py2/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/home/ddjima/anaconda3/envs/py2/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

```

I am using conda python installation, activated python 2.7 before I excute

`conda activate py2`
@demis001

**Comment by averagehat** [comment]
Conda environments and virtual ends don't play nice together. That could be your problem.

Either way you may be better off creating the virtual environment yourself  manually, as that script may be out of date.
